resolver: nightly-2020-06-25

packages:
  - .

extra-deps:
  # numhask-backprop-0.0.1
  - git: https://github.com/tonyday567/numhask-backprop.git
    commit: 972c26b83fbff75438b9276a6e8a801bf100e17f
  - backprop-0.2.6.4
  - box-0.6.0
  - box-csv-0.0.2
  - box-socket-0.0.2
  - chart-svg-0.1.3
  - chart-svg-various-0.0.2
  - gray-code-0.3.1
  - moo-1.2
  - numhask-0.6.0.2
  - numhask-array-0.7.0
  - numhask-space-0.6.0
  - mealy-0.0.1
  - perf-0.7.0
  - vinyl-0.13.0
  - web-rep-0.7.0
