resolver: nightly-2020-11-19

packages:
  - .

extra-deps:
  - numhask-0.7.1.0
  - protolude-0.3.0
  - random-1.2.0
  - splitmix-0.1.0.3
  - numhask-space-0.7.1.0
  - box-0.6.3
  - box-csv-0.0.3
  - numhask-array-0.8.0
  - mealy-0.0.3

  - gray-code-0.3.1
  - moo-1.2

  # chart-svg deps
  - chart-svg-0.2.1
  - formatn-0.0.1
  - reanimate-1.1.3.2
  - reanimate-svg-0.13.0.0
  - hgeometry-0.11.0.0
  - hgeometry-combinatorial-0.11.0.0
  - vinyl-0.13.0

allow-newer: true
